# VERSION 1.0 (apache-superset)
# AUTHOR: Abhishek Sharma<abhioncbr@yahoo.com>
# DESCRIPTION: apache superset docker-compose.yml
# Modified/revamped version of the https://github.com/apache/incubator-superset/blob/master/contrib/docker/docker-compose.yml

version: "3.6"

services:
  redis-ss:
    image: redis:3.2
    restart: always
    # ports:
    #   - 6379:6379
    expose:
      - 6379
    volumes:
      - redis:/data

  mysql-ss:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 6263:3306
    volumes:
      - mysql:/var/lib/mysql

  superset:
    image: abhioncbr/docker-superset:${SUPERSET_VERSION}
    # image: dgleba/docker-superset:${SUPERSET_VERSION}
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SUPERSET_ENV: ${SUPERSET_ENV}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 6361:8088
      - 6362:5555
    depends_on:
      - mysql-ss
      - redis-ss
    volumes:
      - ../ss-config/:/home/superset/config/

volumes:
  mysql:
    external: false
  redis:
    external: false
